name: Main workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version: ['snapshot']
        cask_version: ['snapshot']

    steps:
    - name: Checkout fourclojure.el repo
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install Emacs
      if: steps.cache-emacs.outputs.cache-hit != 'true'
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: DEBUGGING
      run: ls -al ~/.nix-profile/bin

    - name: Install Cask
      uses: conao3/setup-cask@master
      with:
        version: 'snapshot'

    - name: Install dependencies
      run: cask install

    - name: Run tests
      run: cask exec ert-runner
